package echomarket.hibernate;
// Generated Oct 29, 2016 11:54:05 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "addresses")
public class Addresses implements java.io.Serializable {

  private String addressId;
  private String participant_id;
  private String addressLine1;
  private String addressLine2;
  private String postalCode;
  private String city;
  private String province;
  private String usStateId;
  private String region;
  private String countryId;
  private String addressType;

  public Addresses() {
  }

  public Addresses(String addressId, String participant_id, String postalCode) {
    this.addressId = addressId;
    this.participant_id = participant_id;
    this.postalCode = postalCode;
  }

  public Addresses(String addressId, String participant_id, String addressLine1, String addressLine2, String postalCode, String city, String province, String usStateId, String region, String countryId, String addressType) {
    this.addressId = addressId;
    this.participant_id = participant_id;
    this.addressLine1 = addressLine1;
    this.addressLine2 = addressLine2;
    this.postalCode = postalCode;
    this.city = city;
    this.province = province;
    this.usStateId = usStateId;
    this.region = region;
    this.countryId = countryId;
    this.addressType = addressType;
    
  }

  @Id
  public String getAddressId() {
    return this.addressId;
  }

  public void setAddressId(String addressId) {
    this.addressId = addressId;
  }


  public String getAddressLine1() {
    return this.addressLine1;
  }

  public void setAddressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
  }

  public String getAddressLine2() {
    return this.addressLine2;
  }

  public void setAddressLine2(String addressLine2) {
    this.addressLine2 = addressLine2;
  }

  public String getPostalCode() {
    return this.postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public String getCity() {
    return this.city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public String getProvince() {
    return this.province;
  }

  public void setProvince(String province) {
    this.province = province;
  }

  public String getUsStateId() {
    return this.usStateId;
  }

  public void setUsStateId(String usStateId) {
    this.usStateId = usStateId;
  }

  public String getRegion() {
    return this.region;
  }

  public void setRegion(String region) {
    this.region = region;
  }

  public String getCountryId() {
    return this.countryId;
  }

  public void setCountryId(String countryId) {
    this.countryId = countryId;
  }

  public String getAddressType() {
    return this.addressType;
  }

  public void setAddressType(String addressType) {
    this.addressType = addressType;
  }

  /**
   * @return the participant_id
   */
  public String getParticipant_id() {
    return participant_id;
  }

  /**
   * @param participant_id the participant_id to set
   */
  public void setParticipant_id(String participant_id) {
    this.participant_id = participant_id;
  }

}
