package echomarket.hibernate;
// Generated Aug 5, 2016 12:14:14 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name="categories")
public class Categories implements java.io.Serializable {

    @Id
    private int id;
    private String categoryType;

    public Categories() {
    }

    public Categories(String ct) {
        this.categoryType = ct;
    }

    public Categories(int id, String categoryType) {
        this.id = id;
        this.categoryType = categoryType;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCategoryType() {
        return this.categoryType;
    }

    public void setCategoryType(String categoryType) {
        this.categoryType = categoryType;
    }

}
