package echomarket.hibernate;
// Generated Aug 5, 2016 12:14:14 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CommunityMembers generated by hbm2java
 */
@Entity
@Table(name = "communityMembers")
public class CommunityMembers implements java.io.Serializable {

    private String community_member_id;
    private String community_id;
    private String user_id;
    private String remoteIp;
    private String firstName;
    private String mi;
    private String lastName;
    private String alias;
    private Integer isActive;
    private Date dateCreated;
    private Date dateUpdated;
    private Date dateDeleted;
    private Integer isCreator;
    private String email;
    private Integer editable;
    private Integer rowIndex;

    public CommunityMembers() {
    }

    public CommunityMembers(String community_member_id, String community_id, Date dateCreated, Date dateUpdated, Date dateDeleted) {
        this.community_member_id = community_member_id;
        this.community_id = community_id;
        this.dateCreated = dateCreated;
        this.dateUpdated = dateUpdated;
        this.dateDeleted = dateDeleted;
        this.editable = 0;
    }

    public CommunityMembers(String community_member_id, String community_id, String user_id, String remoteIp, String firstName, String lastName, String alias, String email, Integer isActive, Date dateCreated, Date dateUpdated, Integer isCreator) {
        this.community_member_id = community_member_id;
        this.community_id = community_id;
        this.user_id = user_id;
        this.remoteIp = remoteIp;
        this.firstName = firstName;
        this.lastName = lastName;
        this.alias = alias;
        this.email = email;
        this.isActive = isActive;
        this.dateCreated = dateCreated;
        this.dateUpdated = dateUpdated;
        this.isCreator = isCreator;
        this.editable = 0;
    
    }
    
     /// Update constructor
    public CommunityMembers(String community_member_id, String community_id, String user_id,  String remoteIp, String firstName, String lastName, String alias, String email, Integer isActive, Integer isCreator, Date dc) {
        this.community_member_id = community_member_id;
        this.community_id = community_id;
        this.user_id = user_id;
        this.remoteIp = remoteIp;
        this.firstName = firstName;
        this.lastName = lastName;
        this.alias = alias;
        this.email = email;
        this.isActive = isActive;
        this.dateUpdated = new Date();
        this.dateCreated = dc;
        this.isCreator = isCreator;
        this.editable = 0;
    
    }
    public CommunityMembers(String community_member_id, String community_id, String user_id, String firstName, String lastName, String alias, String email, Integer isActive, Date dateCreated, Date dateUpdated, Integer isCreator, Integer rowIndex) {
        this.community_member_id = community_member_id;
        this.community_id = community_id;
        this.user_id = user_id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.alias = alias;
        this.email = email;
        this.isActive = isActive;
        this.dateCreated = dateCreated;
        this.dateUpdated = dateUpdated;
        this.isCreator = isCreator;
        this.editable = 0;
        this.rowIndex = rowIndex;
    
    }
    

    public String getRemoteIp() {
        return this.remoteIp;
    }

    public void setRemoteIp(String remoteIp) {
        this.remoteIp = remoteIp;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getMi() {
        return this.mi;
    }

    public void setMi(String mi) {
        this.mi = mi;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getAlias() {
        return this.alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public Integer getIsActive() {
        return this.isActive;
    }

    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public Date getDateUpdated() {
        return this.dateUpdated;
    }

    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

    public Date getDateDeleted() {
        return this.dateDeleted;
    }

    public void setDateDeleted(Date dateDeleted) {
        this.dateDeleted = dateDeleted;
    }

    public Integer getIsCreator() {
        return this.isCreator;
    }

    public void setIsCreator(Integer isCreator) {
        this.isCreator = isCreator;
    }

    /**
     * @return the community_member_id
     */
    @Id
    public String getCommunity_member_id() {
        return community_member_id;
    }

    /**
     * @param community_member_id the community_member_id to set
     */
    public void setCommunity_member_id(String community_member_id) {
        this.community_member_id = community_member_id;
    }

    /**
     * @return the community_id
     */
    public String getCommunity_id() {
        return community_id;
    }

    /**
     * @param community_id the community_id to set
     */
    public void setCommunity_id(String community_id) {
        this.community_id = community_id;
    }

    /**
     * @return the email
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email the email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * @return the user_id
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * @param user_id the user_id to set
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    /**
     * @return the editable
     */
    public Integer getEditable() {
        return editable;
    }

    /**
     * @param editable the editable to set
     */
    public void setEditable(Integer editable) {
        this.editable = editable;
    }

    /**
     * @return the rowIndex
     */
    public Integer getRowIndex() {
        return rowIndex;
    }

    /**
     * @param rowIndex the rowIndex to set
     */
    public void setRowIndex(Integer rowIndex) {
        this.rowIndex = rowIndex;
    }

}
