package echomarket.hibernate;
// Generated Oct 29, 2016 11:54:05 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Communities generated by hbm2java
 */
public class Communities  implements java.io.Serializable {


     private String communityId;
     private String communityName;
     private Integer approved;
     private String firstName;
     private String mi;
     private String lastName;
     private String addressLine1;
     private String addressLine2;
     private String postalCode;
     private String city;
     private String province;
     private String usStateId;
     private String countryId;
     private String homePhone;
     private String cellPhone;
     private String email;
     private Integer isActive;
     private Date dateCreated;
     private Date dateUpdated;
     private Date dateDeleted;
     private String region;
     private String remoteIp;

    public Communities() {
    }

	
    public Communities(String communityId, String communityName, String firstName, String lastName, String addressLine1, String postalCode, String city, String usStateId, String countryId, Date dateCreated, Date dateUpdated, Date dateDeleted) {
        this.communityId = communityId;
        this.communityName = communityName;
        this.firstName = firstName;
        this.lastName = lastName;
        this.addressLine1 = addressLine1;
        this.postalCode = postalCode;
        this.city = city;
        this.usStateId = usStateId;
        this.countryId = countryId;
        this.dateCreated = dateCreated;
        this.dateUpdated = dateUpdated;
        this.dateDeleted = dateDeleted;
    }
    
    // REgistration constructor
    public Communities(String communityId, String communityName, Integer approved, String firstName, String mi, String lastName, String addressLine1, String addressLine2, String postalCode, String city, String province, String usStateId, String countryId, String homePhone, String cellPhone, String email, Integer isActive, String region, String remoteIp) {
       this.communityId = communityId;
       this.communityName = communityName;
       this.approved = approved;
       this.firstName = firstName;
       this.mi = mi;
       this.lastName = lastName;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.postalCode = postalCode;
       this.city = city;
       this.province = province;
       this.usStateId = usStateId;
       this.countryId = countryId;
       this.homePhone = homePhone;
       this.cellPhone = cellPhone;
       this.email = email;
       this.isActive = isActive;
       this.dateCreated = new Date();
       this.dateUpdated = new Date();
       this.region = region;
       this.remoteIp = remoteIp;
    }
   
    public String getCommunityId() {
        return this.communityId;
    }
    
    public void setCommunityId(String communityId) {
        this.communityId = communityId;
    }
    public String getCommunityName() {
        return this.communityName;
    }
    
    public void setCommunityName(String communityName) {
        this.communityName = communityName;
    }
    public Integer getApproved() {
        return this.approved;
    }
    
    public void setApproved(Integer approved) {
        this.approved = approved;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMi() {
        return this.mi;
    }
    
    public void setMi(String mi) {
        this.mi = mi;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getUsStateId() {
        return this.usStateId;
    }
    
    public void setUsStateId(String usStateId) {
        this.usStateId = usStateId;
    }
    public String getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(String countryId) {
        this.countryId = countryId;
    }
    public String getHomePhone() {
        return this.homePhone;
    }
    
    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }
    public String getCellPhone() {
        return this.cellPhone;
    }
    
    public void setCellPhone(String cellPhone) {
        this.cellPhone = cellPhone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }
    public Date getDateDeleted() {
        return this.dateDeleted;
    }
    
    public void setDateDeleted(Date dateDeleted) {
        this.dateDeleted = dateDeleted;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getRemoteIp() {
        return this.remoteIp;
    }
    
    public void setRemoteIp(String remoteIp) {
        this.remoteIp = remoteIp;
    }




}


