package echomarket.hibernate;
// Generated Oct 29, 2016 11:54:05 AM by Hibernate Tools 4.3.1



/**
 * ContactDescribes generated by hbm2java
 */
public class ContactDescribes  implements java.io.Serializable {


     private String id;
     private String purposeType;
     private int optionValue;
     private String borrowerOrLenderText;

    public ContactDescribes() {
    }

	
    public ContactDescribes(String id, int optionValue) {
        this.id = id;
        this.optionValue = optionValue;
    }
    public ContactDescribes(String id, String purposeType, int optionValue, String borrowerOrLenderText) {
       this.id = id;
       this.purposeType = purposeType;
       this.optionValue = optionValue;
       this.borrowerOrLenderText = borrowerOrLenderText;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getPurposeType() {
        return this.purposeType;
    }
    
    public void setPurposeType(String purposeType) {
        this.purposeType = purposeType;
    }
    public int getOptionValue() {
        return this.optionValue;
    }
    
    public void setOptionValue(int optionValue) {
        this.optionValue = optionValue;
    }
    public String getBorrowerOrLenderText() {
        return this.borrowerOrLenderText;
    }
    
    public void setBorrowerOrLenderText(String borrowerOrLenderText) {
        this.borrowerOrLenderText = borrowerOrLenderText;
    }




}


