package echomarket.hibernate;
// Generated Aug 5, 2016 12:14:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Contacts generated by hbm2java
 */
public class Contacts  implements java.io.Serializable {


     private String contact_id;
     private String subject;
     private String remoteIp;
     private String email;
     private String comments;
     private Date dateCreated;
     private String user_id;

    public Contacts() {
    }

	
    public Contacts(String contactId, String subject, String email, String comments, Date dateCreated) {
        this.contact_id = contactId;
        this.subject = subject;
        this.email = email;
        this.comments = comments;
        this.dateCreated = dateCreated;
    }
    public Contacts(String contactId, String subject, String remoteIp, String email, String comments, Date dateCreated, String user_id) {
       this.contact_id = contactId;
       this.subject = subject;
       this.remoteIp = remoteIp;
       this.email = email;
       this.comments = comments;
       this.dateCreated = dateCreated;
       this.user_id = user_id;
    }
   
    
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getRemoteIp() {
        return this.remoteIp;
    }
    
    public void setRemoteIp(String remoteIp) {
        this.remoteIp = remoteIp;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * @return the contact_id
     */
    public String getContact_id() {
        return contact_id;
    }

    /**
     * @param contact_id the contact_id to set
     */
    public void setContact_id(String contact_id) {
        this.contact_id = contact_id;
    }

    /**
     * @return the user_id
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * @param user_id the user_id to set
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }
    

}


