package echomarket.hibernate;
// Generated Jul 21, 2016 11:09:48 AM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * Purpose generated by hbm2java
 */
@Entity
@Table(name="countries")
public class Countries  implements java.io.Serializable {

    @Id 
    private String countryId;
     private String countryName;
    

    public Countries() {
    }

    public Countries(String id, String cn) {
       this.countryId = id;
       this.countryName = cn;
    }

    
    public String getCountryId() {
        return countryId;
    }

    
    public void setCountryId(String id) {
        this.countryId = id;
    }

    
    public String getCountryName() {
        return countryName;
    }

    
    public void setCountryName(String cName) {
        this.countryName = cName;
    }
    


}


