package echomarket.hibernate;
// Generated Oct 29, 2016 11:54:05 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ItemImages generated by hbm2java
 */
public class ItemImages  implements java.io.Serializable {


     private String itemImagesId;
     private String participantId;
     private String imageContentType;
     private Integer imageHeight;
     private Integer imageWidth;
     private String imageFileName;
     private String itemImageCaption;
     private Date dateCreated;
     private Date dateDeleted;
     private Date dateUpdated;

    public ItemImages() {
    }

	
    public ItemImages(String itemImagesId, String participantId, String imageFileName) {
        this.itemImagesId = itemImagesId;
        this.participantId = participantId;
        this.imageFileName = imageFileName;
        this.dateCreated = dateCreated;
        this.dateDeleted = dateDeleted;
        this.dateUpdated = dateUpdated;
    }
    public ItemImages(String itemImagesId, String participantId, String imageContentType, Integer imageHeight, Integer imageWidth, String imageFileName, String itemImageCaption) {
       this.itemImagesId = itemImagesId;
       this.participantId = participantId;
       this.imageContentType = imageContentType;
       this.imageHeight = imageHeight;
       this.imageWidth = imageWidth;
       this.imageFileName = imageFileName;
       this.itemImageCaption = itemImageCaption;
       
    }
   
    public String getItemImagesId() {
        return this.itemImagesId;
    }
    
    public void setItemImagesId(String itemImagesId) {
        this.itemImagesId = itemImagesId;
    }
    public String getParticipantId() {
        return this.participantId;
    }
    
    public void setParticipantId(String participantId) {
        this.participantId = participantId;
    }
    public String getImageContentType() {
        return this.imageContentType;
    }
    
    public void setImageContentType(String imageContentType) {
        this.imageContentType = imageContentType;
    }
    public Integer getImageHeight() {
        return this.imageHeight;
    }
    
    public void setImageHeight(Integer imageHeight) {
        this.imageHeight = imageHeight;
    }
    public Integer getImageWidth() {
        return this.imageWidth;
    }
    
    public void setImageWidth(Integer imageWidth) {
        this.imageWidth = imageWidth;
    }
    public String getImageFileName() {
        return this.imageFileName;
    }
    
    public void setImageFileName(String imageFileName) {
        this.imageFileName = imageFileName;
    }
    public String getItemImageCaption() {
        return this.itemImageCaption;
    }
    
    public void setItemImageCaption(String itemImageCaption) {
        this.itemImageCaption = itemImageCaption;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getDateDeleted() {
        return this.dateDeleted;
    }
    
    public void setDateDeleted(Date dateDeleted) {
        this.dateDeleted = dateDeleted;
    }
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }




}


