package echomarket.hibernate;
// Generated Aug 5, 2016 12:14:14 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ItemImages generated by hbm2java
 */
@Entity
@Table(name = "item_images")
public class ItemImages implements java.io.Serializable {

    private String id;
    private Borrowers borrowers;
    private String borrowerId;
    private String lenderId;
    private String imageContentType;
    private Integer imageHeight;
    private Integer imageWidth;
    private Integer isActive;
    private Date dateCreated;
    private Date dateDeleted;
    private Date dateUpdated;
    private String imageFileName;
    private String itemImageCaption;
    private String advertiserId;

    public ItemImages() {
    }

    //new ItemImages(tmp_id);
    public ItemImages(String id) {
        this.id = id;
    }

    public ItemImages(String id, Date dateCreated, Date dateDeleted, Date dateUpdated, String imageFileName) {
        this.id = id;
        this.dateCreated = dateCreated;
        this.dateDeleted = dateDeleted;
        this.dateUpdated = dateUpdated;
        this.imageFileName = imageFileName;
    }

    public ItemImages(String id, String borrowerId, String lenderId, String imageContentType, Integer imageHeight, Integer imageWidth, Integer isActive, Date dateCreated, Date dateDeleted, Date dateUpdated, String imageFileName, String itemImageCaption, String advertiserId) {
        this.id = id;
        this.borrowerId = borrowerId;
        this.lenderId = lenderId;
        this.imageContentType = imageContentType;
        this.imageHeight = imageHeight;
        this.imageWidth = imageWidth;
        this.isActive = isActive;
        this.dateCreated = dateCreated;
        this.dateDeleted = dateDeleted;
        this.dateUpdated = dateUpdated;
        this.imageFileName = imageFileName;
        this.itemImageCaption = itemImageCaption;
        this.advertiserId = advertiserId;
    }

//    @OneToMany(mappedBy = "item_images", cascade = CascadeType.ALL)
//    @JoinColumn(name = "user_id")
    

    @Id
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getBorrowerId() {
        return this.borrowerId;
    }

    public void setBorrowerId(String borrowerId) {
        this.borrowerId = borrowerId;
    }

    public String getLenderId() {
        return this.lenderId;
    }

    public void setLenderId(String lenderId) {
        this.lenderId = lenderId;
    }

    public String getImageContentType() {
        return this.imageContentType;
    }

    public void setImageContentType(String imageContentType) {
        this.imageContentType = imageContentType;
    }

    public Integer getImageHeight() {
        return this.imageHeight;
    }

    public void setImageHeight(Integer imageHeight) {
        this.imageHeight = imageHeight;
    }

    public Integer getImageWidth() {
        return this.imageWidth;
    }

    public void setImageWidth(Integer imageWidth) {
        this.imageWidth = imageWidth;
    }

    public Integer getIsActive() {
        return this.isActive;
    }

    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public Date getDateDeleted() {
        return this.dateDeleted;
    }

    public void setDateDeleted(Date dateDeleted) {
        this.dateDeleted = dateDeleted;
    }

    public Date getDateUpdated() {
        return this.dateUpdated;
    }

    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

    public String getImageFileName() {
        return this.imageFileName;
    }

    public void setImageFileName(String imageFileName) {
        this.imageFileName = imageFileName;
    }

    public String getItemImageCaption() {
        return this.itemImageCaption;
    }

    public void setItemImageCaption(String itemImageCaption) {
        this.itemImageCaption = itemImageCaption;
    }

    public String getAdvertiserId() {
        return this.advertiserId;
    }

    public void setAdvertiserId(String advertiserId) {
        this.advertiserId = advertiserId;
    }

    /**
     * @return the borrowers
     */
    @ManyToOne
    @JoinColumn(name = "user_id")
    public Borrowers getBorrowers() {
        return borrowers;
    }

    /**
     * @param borrowers the borrowers to set
     */
    public void setBorrowers(Borrowers borrowers) {
        this.borrowers = borrowers;
    }

    }
