package echomarket.hibernate;
// Generated Oct 29, 2016 11:54:05 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * LenderTransfer generated by hbm2java
 */
public class LenderTransfer  implements java.io.Serializable {


     private String lenderTransferId;
     private String lenderId;
     private String itemId;
     private String userId;
     private String participantId;
     private Integer borrowerComesToWhichAddress;
     private Integer meetBorrowerAtAgreedL2b;
     private Integer meetBorrowerAtAgreedB2l;
     private Integer willDeliverToBorrower;
     private Integer thirdPartyPresenceL2b;
     private Integer thirdPartyPresenceB2l;
     private Integer lenderThirdPartyChoice;
     private Integer borrowerThirdPartyChoice;
     private Integer agreedThirdPartyChoiceL2b;
     private Integer agreedThirdPartyChoiceB2l;
     private Integer borrowerReturnsToWhichAddress;
     private Integer willPickUpPreferredLocationB2l;
     private Integer lenderThirdPartyChoiceB2l;
     private Integer borrowerChoice;
     private Integer forFree;
     private Integer availableForPurchase;
     private BigDecimal availableForPurchaseAmount;
     private Integer smallFee;
     private BigDecimal smallFeeAmount;
     private Integer availableForDonation;
     private Integer donateAnonymous;
     private Integer trade;
     private String tradeItem;
     private Integer agreedNumberOfDays;
     private Integer agreedNumberOfHours;
     private Integer indefiniteDuration;
     private Integer presentDuringBorrowingPeriod;
     private Integer entirePeriod;
     private Integer partialPeriod;
     private Integer provideProperUseTraining;
     private String specificConditions;
     private BigDecimal securityDepositAmount;
     private Integer securityDeposit;
     private String remoteIp;
     private String comment;
     private Date dateCreated;
     private Date dateUpdated;
     private Date dateDeleted;

    public LenderTransfer() {
    }

	
    public LenderTransfer(String lenderTransferId, String lenderId, String itemId, Date dateCreated, Date dateUpdated, Date dateDeleted) {
        this.lenderTransferId = lenderTransferId;
        this.lenderId = lenderId;
        this.itemId = itemId;
        this.dateCreated = dateCreated;
        this.dateUpdated = dateUpdated;
        this.dateDeleted = dateDeleted;
    }
    public LenderTransfer(String lenderTransferId, String lenderId, String itemId, String userId, String participantId, Integer borrowerComesToWhichAddress, Integer meetBorrowerAtAgreedL2b, Integer meetBorrowerAtAgreedB2l, Integer willDeliverToBorrower, Integer thirdPartyPresenceL2b, Integer thirdPartyPresenceB2l, Integer lenderThirdPartyChoice, Integer borrowerThirdPartyChoice, Integer agreedThirdPartyChoiceL2b, Integer agreedThirdPartyChoiceB2l, Integer borrowerReturnsToWhichAddress, Integer willPickUpPreferredLocationB2l, Integer lenderThirdPartyChoiceB2l, Integer borrowerChoice, Integer forFree, Integer availableForPurchase, BigDecimal availableForPurchaseAmount, Integer smallFee, BigDecimal smallFeeAmount, Integer availableForDonation, Integer donateAnonymous, Integer trade, String tradeItem, Integer agreedNumberOfDays, Integer agreedNumberOfHours, Integer indefiniteDuration, Integer presentDuringBorrowingPeriod, Integer entirePeriod, Integer partialPeriod, Integer provideProperUseTraining, String specificConditions, BigDecimal securityDepositAmount, Integer securityDeposit, String remoteIp, String comment, Date dateCreated, Date dateUpdated, Date dateDeleted) {
       this.lenderTransferId = lenderTransferId;
       this.lenderId = lenderId;
       this.itemId = itemId;
       this.userId = userId;
       this.participantId = participantId;
       this.borrowerComesToWhichAddress = borrowerComesToWhichAddress;
       this.meetBorrowerAtAgreedL2b = meetBorrowerAtAgreedL2b;
       this.meetBorrowerAtAgreedB2l = meetBorrowerAtAgreedB2l;
       this.willDeliverToBorrower = willDeliverToBorrower;
       this.thirdPartyPresenceL2b = thirdPartyPresenceL2b;
       this.thirdPartyPresenceB2l = thirdPartyPresenceB2l;
       this.lenderThirdPartyChoice = lenderThirdPartyChoice;
       this.borrowerThirdPartyChoice = borrowerThirdPartyChoice;
       this.agreedThirdPartyChoiceL2b = agreedThirdPartyChoiceL2b;
       this.agreedThirdPartyChoiceB2l = agreedThirdPartyChoiceB2l;
       this.borrowerReturnsToWhichAddress = borrowerReturnsToWhichAddress;
       this.willPickUpPreferredLocationB2l = willPickUpPreferredLocationB2l;
       this.lenderThirdPartyChoiceB2l = lenderThirdPartyChoiceB2l;
       this.borrowerChoice = borrowerChoice;
       this.forFree = forFree;
       this.availableForPurchase = availableForPurchase;
       this.availableForPurchaseAmount = availableForPurchaseAmount;
       this.smallFee = smallFee;
       this.smallFeeAmount = smallFeeAmount;
       this.availableForDonation = availableForDonation;
       this.donateAnonymous = donateAnonymous;
       this.trade = trade;
       this.tradeItem = tradeItem;
       this.agreedNumberOfDays = agreedNumberOfDays;
       this.agreedNumberOfHours = agreedNumberOfHours;
       this.indefiniteDuration = indefiniteDuration;
       this.presentDuringBorrowingPeriod = presentDuringBorrowingPeriod;
       this.entirePeriod = entirePeriod;
       this.partialPeriod = partialPeriod;
       this.provideProperUseTraining = provideProperUseTraining;
       this.specificConditions = specificConditions;
       this.securityDepositAmount = securityDepositAmount;
       this.securityDeposit = securityDeposit;
       this.remoteIp = remoteIp;
       this.comment = comment;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
       this.dateDeleted = dateDeleted;
    }
   
    public String getLenderTransferId() {
        return this.lenderTransferId;
    }
    
    public void setLenderTransferId(String lenderTransferId) {
        this.lenderTransferId = lenderTransferId;
    }
    public String getLenderId() {
        return this.lenderId;
    }
    
    public void setLenderId(String lenderId) {
        this.lenderId = lenderId;
    }
    public String getItemId() {
        return this.itemId;
    }
    
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getParticipantId() {
        return this.participantId;
    }
    
    public void setParticipantId(String participantId) {
        this.participantId = participantId;
    }
    public Integer getBorrowerComesToWhichAddress() {
        return this.borrowerComesToWhichAddress;
    }
    
    public void setBorrowerComesToWhichAddress(Integer borrowerComesToWhichAddress) {
        this.borrowerComesToWhichAddress = borrowerComesToWhichAddress;
    }
    public Integer getMeetBorrowerAtAgreedL2b() {
        return this.meetBorrowerAtAgreedL2b;
    }
    
    public void setMeetBorrowerAtAgreedL2b(Integer meetBorrowerAtAgreedL2b) {
        this.meetBorrowerAtAgreedL2b = meetBorrowerAtAgreedL2b;
    }
    public Integer getMeetBorrowerAtAgreedB2l() {
        return this.meetBorrowerAtAgreedB2l;
    }
    
    public void setMeetBorrowerAtAgreedB2l(Integer meetBorrowerAtAgreedB2l) {
        this.meetBorrowerAtAgreedB2l = meetBorrowerAtAgreedB2l;
    }
    public Integer getWillDeliverToBorrower() {
        return this.willDeliverToBorrower;
    }
    
    public void setWillDeliverToBorrower(Integer willDeliverToBorrower) {
        this.willDeliverToBorrower = willDeliverToBorrower;
    }
    public Integer getThirdPartyPresenceL2b() {
        return this.thirdPartyPresenceL2b;
    }
    
    public void setThirdPartyPresenceL2b(Integer thirdPartyPresenceL2b) {
        this.thirdPartyPresenceL2b = thirdPartyPresenceL2b;
    }
    public Integer getThirdPartyPresenceB2l() {
        return this.thirdPartyPresenceB2l;
    }
    
    public void setThirdPartyPresenceB2l(Integer thirdPartyPresenceB2l) {
        this.thirdPartyPresenceB2l = thirdPartyPresenceB2l;
    }
    public Integer getLenderThirdPartyChoice() {
        return this.lenderThirdPartyChoice;
    }
    
    public void setLenderThirdPartyChoice(Integer lenderThirdPartyChoice) {
        this.lenderThirdPartyChoice = lenderThirdPartyChoice;
    }
    public Integer getBorrowerThirdPartyChoice() {
        return this.borrowerThirdPartyChoice;
    }
    
    public void setBorrowerThirdPartyChoice(Integer borrowerThirdPartyChoice) {
        this.borrowerThirdPartyChoice = borrowerThirdPartyChoice;
    }
    public Integer getAgreedThirdPartyChoiceL2b() {
        return this.agreedThirdPartyChoiceL2b;
    }
    
    public void setAgreedThirdPartyChoiceL2b(Integer agreedThirdPartyChoiceL2b) {
        this.agreedThirdPartyChoiceL2b = agreedThirdPartyChoiceL2b;
    }
    public Integer getAgreedThirdPartyChoiceB2l() {
        return this.agreedThirdPartyChoiceB2l;
    }
    
    public void setAgreedThirdPartyChoiceB2l(Integer agreedThirdPartyChoiceB2l) {
        this.agreedThirdPartyChoiceB2l = agreedThirdPartyChoiceB2l;
    }
    public Integer getBorrowerReturnsToWhichAddress() {
        return this.borrowerReturnsToWhichAddress;
    }
    
    public void setBorrowerReturnsToWhichAddress(Integer borrowerReturnsToWhichAddress) {
        this.borrowerReturnsToWhichAddress = borrowerReturnsToWhichAddress;
    }
    public Integer getWillPickUpPreferredLocationB2l() {
        return this.willPickUpPreferredLocationB2l;
    }
    
    public void setWillPickUpPreferredLocationB2l(Integer willPickUpPreferredLocationB2l) {
        this.willPickUpPreferredLocationB2l = willPickUpPreferredLocationB2l;
    }
    public Integer getLenderThirdPartyChoiceB2l() {
        return this.lenderThirdPartyChoiceB2l;
    }
    
    public void setLenderThirdPartyChoiceB2l(Integer lenderThirdPartyChoiceB2l) {
        this.lenderThirdPartyChoiceB2l = lenderThirdPartyChoiceB2l;
    }
    public Integer getBorrowerChoice() {
        return this.borrowerChoice;
    }
    
    public void setBorrowerChoice(Integer borrowerChoice) {
        this.borrowerChoice = borrowerChoice;
    }
    public Integer getForFree() {
        return this.forFree;
    }
    
    public void setForFree(Integer forFree) {
        this.forFree = forFree;
    }
    public Integer getAvailableForPurchase() {
        return this.availableForPurchase;
    }
    
    public void setAvailableForPurchase(Integer availableForPurchase) {
        this.availableForPurchase = availableForPurchase;
    }
    public BigDecimal getAvailableForPurchaseAmount() {
        return this.availableForPurchaseAmount;
    }
    
    public void setAvailableForPurchaseAmount(BigDecimal availableForPurchaseAmount) {
        this.availableForPurchaseAmount = availableForPurchaseAmount;
    }
    public Integer getSmallFee() {
        return this.smallFee;
    }
    
    public void setSmallFee(Integer smallFee) {
        this.smallFee = smallFee;
    }
    public BigDecimal getSmallFeeAmount() {
        return this.smallFeeAmount;
    }
    
    public void setSmallFeeAmount(BigDecimal smallFeeAmount) {
        this.smallFeeAmount = smallFeeAmount;
    }
    public Integer getAvailableForDonation() {
        return this.availableForDonation;
    }
    
    public void setAvailableForDonation(Integer availableForDonation) {
        this.availableForDonation = availableForDonation;
    }
    public Integer getDonateAnonymous() {
        return this.donateAnonymous;
    }
    
    public void setDonateAnonymous(Integer donateAnonymous) {
        this.donateAnonymous = donateAnonymous;
    }
    public Integer getTrade() {
        return this.trade;
    }
    
    public void setTrade(Integer trade) {
        this.trade = trade;
    }
    public String getTradeItem() {
        return this.tradeItem;
    }
    
    public void setTradeItem(String tradeItem) {
        this.tradeItem = tradeItem;
    }
    public Integer getAgreedNumberOfDays() {
        return this.agreedNumberOfDays;
    }
    
    public void setAgreedNumberOfDays(Integer agreedNumberOfDays) {
        this.agreedNumberOfDays = agreedNumberOfDays;
    }
    public Integer getAgreedNumberOfHours() {
        return this.agreedNumberOfHours;
    }
    
    public void setAgreedNumberOfHours(Integer agreedNumberOfHours) {
        this.agreedNumberOfHours = agreedNumberOfHours;
    }
    public Integer getIndefiniteDuration() {
        return this.indefiniteDuration;
    }
    
    public void setIndefiniteDuration(Integer indefiniteDuration) {
        this.indefiniteDuration = indefiniteDuration;
    }
    public Integer getPresentDuringBorrowingPeriod() {
        return this.presentDuringBorrowingPeriod;
    }
    
    public void setPresentDuringBorrowingPeriod(Integer presentDuringBorrowingPeriod) {
        this.presentDuringBorrowingPeriod = presentDuringBorrowingPeriod;
    }
    public Integer getEntirePeriod() {
        return this.entirePeriod;
    }
    
    public void setEntirePeriod(Integer entirePeriod) {
        this.entirePeriod = entirePeriod;
    }
    public Integer getPartialPeriod() {
        return this.partialPeriod;
    }
    
    public void setPartialPeriod(Integer partialPeriod) {
        this.partialPeriod = partialPeriod;
    }
    public Integer getProvideProperUseTraining() {
        return this.provideProperUseTraining;
    }
    
    public void setProvideProperUseTraining(Integer provideProperUseTraining) {
        this.provideProperUseTraining = provideProperUseTraining;
    }
    public String getSpecificConditions() {
        return this.specificConditions;
    }
    
    public void setSpecificConditions(String specificConditions) {
        this.specificConditions = specificConditions;
    }
    public BigDecimal getSecurityDepositAmount() {
        return this.securityDepositAmount;
    }
    
    public void setSecurityDepositAmount(BigDecimal securityDepositAmount) {
        this.securityDepositAmount = securityDepositAmount;
    }
    public Integer getSecurityDeposit() {
        return this.securityDeposit;
    }
    
    public void setSecurityDeposit(Integer securityDeposit) {
        this.securityDeposit = securityDeposit;
    }
    public String getRemoteIp() {
        return this.remoteIp;
    }
    
    public void setRemoteIp(String remoteIp) {
        this.remoteIp = remoteIp;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }
    public Date getDateDeleted() {
        return this.dateDeleted;
    }
    
    public void setDateDeleted(Date dateDeleted) {
        this.dateDeleted = dateDeleted;
    }




}


