package echomarket.hibernate;
// Generated Aug 5, 2016 12:14:14 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Categories generated by hbm2java
 */

public class Map implements java.io.Serializable {

    private Integer id;
    private String key_text;
    private String value_text;

    public Map() {
    }

    public Map(String key, String value) {
        this.key_text = key;
        this.value_text = value;
    }

    /**
     * @return the id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the key_text
     */
    public String getKey_text() {
        return key_text;
    }

    /**
     * @param key_text the key_text to set
     */
    public void setKey_text(String key_text) {
        this.key_text = key_text;
    }

    /**
     * @return the value_text
     */
    public String getValue_text() {
        return value_text;
    }

    /**
     * @param value_text the value_text to set
     */
    public void setValue_text(String value_text) {
        this.value_text = value_text;
    }

}