package echomarket.hibernate;
// Generated Aug 5, 2016 12:14:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PartyRelationships generated by hbm2java
 */
public class PartyRelationships  implements java.io.Serializable {


     private Integer id;
     private Integer partyId;
     private Integer customerTypeId;
     private Date createdAt;
     private Date updatedAt;
     private Integer relation;

    public PartyRelationships() {
    }

	
    public PartyRelationships(Date createdAt, Date updatedAt) {
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public PartyRelationships(Integer partyId, Integer customerTypeId, Date createdAt, Date updatedAt, Integer relation) {
       this.partyId = partyId;
       this.customerTypeId = customerTypeId;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.relation = relation;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getPartyId() {
        return this.partyId;
    }
    
    public void setPartyId(Integer partyId) {
        this.partyId = partyId;
    }
    public Integer getCustomerTypeId() {
        return this.customerTypeId;
    }
    
    public void setCustomerTypeId(Integer customerTypeId) {
        this.customerTypeId = customerTypeId;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Integer getRelation() {
        return this.relation;
    }
    
    public void setRelation(Integer relation) {
        this.relation = relation;
    }




}


