package echomarket.hibernate;
// Generated Oct 29, 2016 11:54:05 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Searches generated by hbm2java
 */
public class Searches  implements java.io.Serializable {


     private String id;
     private String keyword;
     private String postalCode;
     private Date createdAt;
     private Date updatedAt;
     private Integer categoryId;
     private Date startDate;
     private Date endDate;
     private Integer lenderOrBorrower;
     private int isCommunity;
     private String userId;
     private Integer zipCodeRadius;
     private String remoteIp;

    public Searches() {
    }

	
    public Searches(String id, Date createdAt, Date updatedAt, int isCommunity, String userId) {
        this.id = id;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.isCommunity = isCommunity;
        this.userId = userId;
    }
    public Searches(String id, String keyword, String postalCode, Date createdAt, Date updatedAt, Integer categoryId, Date startDate, Date endDate, Integer lenderOrBorrower, int isCommunity, String userId, Integer zipCodeRadius, String remoteIp) {
       this.id = id;
       this.keyword = keyword;
       this.postalCode = postalCode;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.categoryId = categoryId;
       this.startDate = startDate;
       this.endDate = endDate;
       this.lenderOrBorrower = lenderOrBorrower;
       this.isCommunity = isCommunity;
       this.userId = userId;
       this.zipCodeRadius = zipCodeRadius;
       this.remoteIp = remoteIp;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getKeyword() {
        return this.keyword;
    }
    
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Integer getLenderOrBorrower() {
        return this.lenderOrBorrower;
    }
    
    public void setLenderOrBorrower(Integer lenderOrBorrower) {
        this.lenderOrBorrower = lenderOrBorrower;
    }
    public int getIsCommunity() {
        return this.isCommunity;
    }
    
    public void setIsCommunity(int isCommunity) {
        this.isCommunity = isCommunity;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Integer getZipCodeRadius() {
        return this.zipCodeRadius;
    }
    
    public void setZipCodeRadius(Integer zipCodeRadius) {
        this.zipCodeRadius = zipCodeRadius;
    }
    public String getRemoteIp() {
        return this.remoteIp;
    }
    
    public void setRemoteIp(String remoteIp) {
        this.remoteIp = remoteIp;
    }




}


