package echomarket.hibernate;
// Generated Aug 5, 2016 12:14:14 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Searches generated by hbm2java
 */
@Entity
@Table(name = "searches")
public class Searches implements java.io.Serializable {

    private String id;
    private String keyword;
    private String postalCode;
    private Date createdAt;
    private Date updatedAt;
    private Integer categoryId;
    private Date startDate;
    private Date endDate;
    private Integer lenderOrBorrower;
    private int isCommunity;
    private String user_id;
    private Integer zipCodeRadius;
    private String remoteIp;

    public Searches() {
    }

    public Searches(String id, Date createdAt, Date updatedAt, int isCommunity, String user_id) {
        this.id = id;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.isCommunity = isCommunity;
        this.user_id = user_id;
    }

    public Searches(String id, String keyword, String postalCode, Date createdAt, Date updatedAt, Integer categoryId, Date startDate, Date endDate, Integer lenderOrBorrower, int isCommunity, String user_id, Integer zipCodeRadius, String remoteIp) {
        this.id = id;
        this.keyword = keyword;
        this.postalCode = postalCode;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.categoryId = categoryId;
        this.startDate = startDate;
        this.endDate = endDate;
        this.lenderOrBorrower = lenderOrBorrower;
        this.isCommunity = isCommunity;
        this.user_id = user_id;
        this.zipCodeRadius = zipCodeRadius;
        this.remoteIp = remoteIp;
    }

    @Id
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getKeyword() {
        return this.keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public String getPostalCode() {
        return this.postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Integer getLenderOrBorrower() {
        return this.lenderOrBorrower;
    }

    public void setLenderOrBorrower(Integer lenderOrBorrower) {
        this.lenderOrBorrower = lenderOrBorrower;
    }

    public int getIsCommunity() {
        return this.isCommunity;
    }

    public void setIsCommunity(int isCommunity) {
        this.isCommunity = isCommunity;
    }

    public String getuser_id() {
        return this.user_id;
    }

    public void setuser_id(String user_id) {
        this.user_id = user_id;
    }

    public Integer getZipCodeRadius() {
        return this.zipCodeRadius;
    }

    public void setZipCodeRadius(Integer zipCodeRadius) {
        this.zipCodeRadius = zipCodeRadius;
    }

    public String getRemoteIp() {
        return this.remoteIp;
    }

    public void setRemoteIp(String remoteIp) {
        this.remoteIp = remoteIp;
    }

}
