package echomarket.hibernate;
// Generated Aug 5, 2016 12:14:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserTransactions generated by hbm2java
 */
public class UserTransactions  implements java.io.Serializable {


     private Integer id;
     private Integer userId;
     private Integer ledgerLineId;
     private Long lineItemAmount;
     private Date createdAt;
     private Date updatedAt;
     private Integer ledgerId;

    public UserTransactions() {
    }

	
    public UserTransactions(Date createdAt, Date updatedAt) {
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public UserTransactions(Integer userId, Integer ledgerLineId, Long lineItemAmount, Date createdAt, Date updatedAt, Integer ledgerId) {
       this.userId = userId;
       this.ledgerLineId = ledgerLineId;
       this.lineItemAmount = lineItemAmount;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.ledgerId = ledgerId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Integer getLedgerLineId() {
        return this.ledgerLineId;
    }
    
    public void setLedgerLineId(Integer ledgerLineId) {
        this.ledgerLineId = ledgerLineId;
    }
    public Long getLineItemAmount() {
        return this.lineItemAmount;
    }
    
    public void setLineItemAmount(Long lineItemAmount) {
        this.lineItemAmount = lineItemAmount;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Integer getLedgerId() {
        return this.ledgerId;
    }
    
    public void setLedgerId(Integer ledgerId) {
        this.ledgerId = ledgerId;
    }




}


