package echomarket.hibernate;
// Generated Jul 21, 2016 11:09:48 AM by Hibernate Tools 4.3.1

import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.UUID;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users")
public class Users implements java.io.Serializable {

    @Id
    private String id;
    private String username;
    private String email;
    private Date createdAt;
    private Date updatedAt;
    private String remoteIp;
    private byte[] cryptedPassword;
    private byte[] salt;
    private String resetCode;
    private Date activatedAt;
    private String userAlias;
    private String userType;
    private int isRapid;
    private Integer roleId;
    private String firstName;
    private String lastName;
    private Integer isCommunity;

    public Users() {
    }

    //create_record = new Users(assign_id, firstName, lastName, username, userAlias, password, email, userType );
    // THis constructor is used to create new, non-activated user
    public Users(String id,String firstName, String lastName, String userName, String userAlias, String password, String email, String userType, Integer isCommunity) {
        String local_password = password;
        Date today = new Date();
        this.id = id;
        this.username = userName;
        this.email = email;
        this.userAlias = userAlias;
        this.userType = userType;
        this.isRapid = 0;
        this.firstName = firstName;
        this.lastName = lastName;
        this.salt = passTheSalt();
        this.cryptedPassword = passThePepper(password);
        // Later make sure this is unique in database
        this.resetCode = BuildRandomValue();
        this.activatedAt = null;
        this.isCommunity = isCommunity;
        this.createdAt = today;

    }

    public Users(String id,String username, String email, String userAlias, String userType, int isRapid, String firstName, String lastName) {
        this.id = id;
        this.username = username;
        this.email = email;
        this.userAlias = userAlias;
        this.userType = userType;
        this.isRapid = isRapid;
        this.firstName = firstName;
        this.lastName = lastName;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getRemoteIp() {
        return this.remoteIp;
    }

    public void setRemoteIp(String remoteIp) {
        this.remoteIp = remoteIp;
    }

    public byte[] getCryptedPassword() {
        return this.cryptedPassword;
    }

    public void setCryptedPassword(byte[] cryptedPassword) {
        this.cryptedPassword = cryptedPassword;
    }

    public byte[] getSalt() {
        return this.salt;
    }

    public void setSalt(byte[] salt) {
        this.salt = salt;
    }

    public String getResetCode() {
        return this.resetCode;
    }

    public void setResetCode(String resetCode) {
        this.resetCode = resetCode;
    }

    public Date getActivatedAt() {
        return this.activatedAt;
    }

    public void setActivatedAt(Date activatedAt) {
        this.activatedAt = activatedAt;
    }

    public String getUserAlias() {
        return this.userAlias;
    }

    public void setUserAlias(String userAlias) {
        this.userAlias = userAlias;
    }

    public String getUserType() {
        return this.userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    public int getIsRapid() {
        return this.isRapid;
    }

    public void setIsRapid(int isRapid) {
        this.isRapid = isRapid;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    private byte[] passThePepper(String password) {

        byte[] result = new byte[8];
        PasswordEncryptionService pes = new PasswordEncryptionService();

        try {
            result = pes.getEncryptedPassword(password, this.salt);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Users.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidKeySpecException ex) {
            Logger.getLogger(Users.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.cryptedPassword = result;
        return result;

    }

    private byte[] passTheSalt() {

        byte[] shaker = new byte[8];
        PasswordEncryptionService pes = new PasswordEncryptionService();
//
        try {
            shaker = pes.generateSalt();

        } catch (NoSuchAlgorithmException e) {
        }
        pes = null;
        this.salt = shaker;
        return shaker;
    }

    public String BuildRandomValue() {

        String uuid = UUID.randomUUID().toString();
        return uuid;

    }

    /**
     * @return the isCommunity
     */
    public Integer getIsCommunity() {
        return isCommunity;
    }

    /**
     * @param isCommunity the isCommunity to set
     */
    public void setIsCommunity(Integer isCommunity) {
        this.isCommunity = isCommunity;
    }

}
