package echomarket.hibernate;
// Generated Aug 5, 2016 12:14:14 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UsStates generated by hbm2java
 */
@Entity
@Table(name = "us_states")
public class UsStates implements java.io.Serializable {

    @Id
    private String id;
    private String stateName;

    public UsStates() {
    }

    public UsStates(String id) {
        this.id = id;
    }

    public UsStates(String id, String stateName) {
        this.id = id;
        this.stateName = stateName;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getStateName() {
        return this.stateName;
    }

    public void setStateName(String stateName) {
        this.stateName = stateName;
    }

}
